name: Run Tests with Strawberry Perl

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    env:
      AUTHOR_TESTING: 1
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5'
          - '5.32'
        os: ['windows-latest']
    name: Strawberry Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: 'strawberry'
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install author deps
        run: |
          cpanm -qn Dist::Zilla
          dzil authordeps | cpanm -qn
          dzil listdeps --author | cpanm -qn
      - name: Build dist
        run: |
          dzil build --in build-dir
      - name: Install Perl deps
        run: |
          cd build-dir
          cpanm --verbose --notest --installdeps .
          cd ..
      - name: Run tests
        run: |
          cd build-dir
          cpanm --verbose --test-only .
