name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    env:
      AUTHOR_TESTING: 1
    strategy:
      matrix:
        os: ['windows-latest']
    name: Strawberry Perl on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: 'strawberry'
      - run: perl -V
      - name: Install author deps
        run: |
          cpanm -qn Dist::Zilla
          dzil authordeps | cpanm -qn
          dzil listdeps --author | cpanm -qn
      - name: Build dist
        run: |
          dzil build --in build-dir
      - name: Install Perl deps
        run: |
          cd build-dir
          cpanm --verbose --notest --installdeps .
          cd ..
      - name: Run tests
        run: |
          cd build-dir
          cpanm --verbose --test-only .
